import Link from "next/link";
import { DisclaimerBanner } from "@/components/ui/DisclaimerBanner";
const demos = [
  { number: "01", icon: "✳", name: "BrightSmile Dental", category: "DENTAL CARE", description: "Everyday questions, a warmer welcome, and a clear path to an appointment request.", slug: "dental", color: "teal", tags: "Service FAQs / Appointment requests" },
  { number: "02", icon: "⌂", name: "Harbor Homes", category: "REAL ESTATE", description: "Turn buying and renting preferences into a useful conversation with a broker.", slug: "real-estate", color: "navy", tags: "Lead qualification / Broker handoff" },
  { number: "03", icon: "↗", name: "FixRight Home Services", category: "HOME SERVICES", description: "Understand the problem, collect the essentials, and help customers take the next step.", slug: "home-services", color: "orange", tags: "Quote requests / Service triage" },
];
export default function CasePage() {
  return <><DisclaimerBanner /><div className="case-shell"><header className="site-header"><Link href="/" className="wordmark"><img src="/ambern-logo.svg" alt="Ambern" /></Link><nav aria-label="Main navigation"><a href="#demos">Explore demos</a><a href="#approach">Our approach</a><a className="nav-contact" href="#contact">Let’s talk ↗</a></nav></header><main id="main">
    <section className="case-hero"><div className="hero-copy"><span className="eyebrow"><span className="small-dot" /> SELECTED WORK / INTERACTIVE PORTFOLIO</span><h1>AI Chatbots for<br /><span>Small Businesses</span><span className="hero-period">.</span></h1><p>Better first conversations.<br />Built around the way your business works.</p><a className="primary-button" href="#demos">Try the three demos <span>↗</span></a><div className="hero-caption">THREE FICTIONAL BUSINESSES. ONE SHARED ENGINE.</div></div><div className="hero-art" aria-label="Illustration of a conversation routed to a specialist"><div className="art-top"><span className="small-dot" /> A BETTER FIRST RESPONSE<span>01—03</span></div><div className="art-message art-question">“Can you help me get started?”</div><div className="art-connector" /><div className="engine-node"><span>✳</span><div>One assistant.<small>The right next step.</small></div></div><div className="art-branches"><span>Answer</span><span>Qualify</span><span>Connect</span></div><p className="art-footer">Thoughtful conversations. Clear boundaries.</p></div></section>
    <section className="problem-strip"><span className="eyebrow">THE OPPORTUNITY</span><p>Small teams can’t be everywhere.<br /><strong>A useful first response can be.</strong></p><p>Enquiries arrive while teams are on a job, with a patient, or away from the desk. Ambern built one configurable assistant engine to answer routine questions and collect the details a person needs next.</p></section>
    <section id="demos" className="section"><div className="section-heading"><div><span className="eyebrow">01 / EXPLORE THE EXPERIENCE</span><h2>Three businesses.<br />Three ways to start.</h2></div><p>Working demonstrations, built for exploration.<br />Choose a business and use fictional details.</p></div><div className="demo-cards">{demos.map(demo => <article key={demo.slug} className={`demo-card ${demo.color}`}><div className="card-top"><span>{demo.category}</span><span>{demo.number}</span></div><div className="card-symbol" aria-hidden="true">{demo.icon}</div><h3>{demo.name}</h3><p>{demo.description}</p><div className="card-tags">{demo.tags}</div><Link href={`/demos/${demo.slug}-chatbot`}>Try the demo <span>↗</span></Link></article>)}</div></section>
    <section id="approach" className="section architecture"><span className="eyebrow">02 / BUILT TO BE REUSED</span><div className="section-heading"><h2>One engine.<br />A considered next step.</h2><p>Each business has its own knowledge, qualification fields, and visual identity. The same validated conversation flow connects them all.</p></div><div className="architecture-flow" aria-label="Message to router to specialist to validation and confirmation"><span>Customer message</span><b aria-hidden="true">→</b><span>Router</span><b aria-hidden="true">→</b><span>Specialist</span><b aria-hidden="true">→</b><span>Validate + confirm</span></div><div className="agent-grid">{[["Router", "Identifies the intent and selects the next specialist."], ["FAQ", "Answers from the active business’s knowledge base and admits uncertainty."], ["Lead qualification", "Collects one detail at a time, then asks you to review."], ["Booking", "Collects a service, date, and period for a simulated request."], ["Human handoff", "Records a confirmed request for a person; no live transfer occurs."]].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="tech-list" aria-label="Technologies">{["Next.js", "TypeScript", "Tailwind CSS", "OpenRouter · server-side", "Drizzle / PostgreSQL", "Vitest", "Playwright"].map(tech => <span key={tech}>{tech}</span>)}</div></section>
    <section className="section details-grid"><article><span className="eyebrow">03 / TRUST BY DESIGN</span><h2>Useful, with boundaries.</h2><p>API credentials stay on the server. Requests and structured responses are validated, messages are rate limited, and each business uses a separate knowledge base.</p><p>Lead and booking details require confirmation. Demo records expire within 24 hours; the interface keeps history only for the current page session. Please enter fictional information only.</p></article><article><span className="eyebrow">WHAT THIS DEMO DOESN’T DO</span><h3>A demonstration, not a deployment.</h3><p>No real appointment, property availability, price quote, or human contact is arranged. Calendar, CRM, email, and WhatsApp integrations require a separate implementation.</p><p>Without an API key, replies are deterministic and clearly labelled as scripted. Dental answers are administrative only. No medical diagnosis or prescription is offered.</p></article></section>
    <section className="section verification"><span className="eyebrow">04 / VERIFICATION</span><h2>Explore the working product.</h2><p>The live demos above are the source of truth for the interaction. Automated verification covers conversation routing, knowledge isolation, confirmation flows, input protection, provider failures, mobile layouts, and accessibility. Execution results are recorded in the project’s delivery report.</p><p className="muted">Screenshots are added after browser verification; no mockup is presented as a product capture.</p></section>
    <section id="contact" className="contact-section"><div><span className="eyebrow">HAVE A SIMILAR WORKFLOW?</span><h2>Make your first response<br />a better one.</h2><p>Contact Ambern through the channel where you found this portfolio. Share your business type, common enquiries, and the tools your team uses.</p></div><aside className="estimate-card"><span className="eyebrow">INDICATIVE SCOPE</span><p>Typical implementation estimate:<strong>AUD $750–$1,500</strong></p><p>Typical delivery estimate:<strong>7–10 business days</strong></p><small>Estimates for a similar implementation, subject to scope. These are not amounts paid by clients or past delivery results.</small></aside></section>
  </main><footer className="site-footer"><Link className="wordmark" href="/"><img src="/ambern-logo.svg" alt="Ambern" /></Link><p>Independent thinking. Useful digital experiences.</p><a href="#main">Back to top ↑</a></footer></div></>;
}
